import Head from 'next/head'

export const Top = () => {
  return (
    <div>
      <Head>
        <title>a</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </div>
      </main>
    </div>
  )
}
